### ISSUE TITLE
Add Be a Mentor registration route

### ISSUE THREAD

**Issue by imabp** [Tech-Phantoms/Tech_Phantoms_website#108]
**We don't have route for member and mentor registrations**
As the community is growing, people would love to join us as member or as mentor, but are not able to find the link for registration. So implementing a custom form for mentor and member registrations.

**Describe the solution you'd like**
A route which renders Member registration side

**Additional context**
UI need to be designed.

**Comment by Harshchourasiya** [comment]
> **We don't have route for member and mentor registrations**
> As the community is growing, people would love to join us as member or as mentor, but are not able to find the link for registration. So implementing a custom form for mentor and member registrations.
> 
> **Describe the solution you'd like**
> A route which renders Member registration side
> 
> **Additional context**
> UI need to be designed.

Hey, I like to work on this idea but Which Type of backend we use here and what we want to take from a member and mentor and where we want to store the data

**Comment by imabp** [comment]
We are planning to work on this issue in this weekend.

**Comment by Harshchourasiya** [comment]
Hey, Do you need help in this issue

**Comment by Harshchourasiya** [comment]
> We are planning to work on this issue in this weekend.

Hey, Do you need help in this issue.
