### ISSUE TITLE
Create a React Higer Order Component for page loader

### ISSUE THREAD

**Issue by imabp** [Tech-Phantoms/Tech_Phantoms_website#150]
Sometimes, fetching data from airtable, takes time, so I come up with a idea, to have a page loader animation as Higer Order Component which will help user to see the fully rendered content.

**Comment by imabp** [comment]
I am working on this issue, on a branch name `imabp-feat/loader`

**Comment by Souvikns** [comment]
I guess rather than creating a higher-order component just add the loader animation in `app.js` and control the state using redux or kladi.
