### ISSUE TITLE
Event alert feature for event section (Feature Request) 

### ISSUE THREAD

**Issue by Harshchourasiya** [Tech-Phantoms/Tech_Phantoms_website#155]
**Is your feature request related to a problem? Please describe.**

This feature is not related to any problem.

**Describe the solution you'd like**

In this feature we will ask our visitors for their email addresses so whenever an event will be updated they will get an automated email alert.

**benefit of this feature**

> Increase our community networks.

> Promote beginner to get involved in events.  

**Would, you like to work on**

Yes, I love to work on this feature with the help of experts of this community

**Comment by imabp** [comment]
Great feature. 
I was thinking about it.
But before that would you like to see the issue #158

**Comment by atharvagadkari05** [comment]
I'm interested in this issue, can you assign me this?

**Comment by vinitshahdeo** [comment]
@imabp This will be a great add-on for lead generation. Go for it. 🚀
