### ISSUE TITLE
Revamp Event Page

### ISSUE THREAD

**Issue by imabp** [Tech-Phantoms/Tech_Phantoms_website#158]
```js
Notice: "Do NOT use custom CSS, until and unless its an urgent for FLEX and MARGIN properties. "
We ❤ Chakra UI
Send PR to development only
*This issue needs precision work*
```

## Screenshots
![image](https://user-images.githubusercontent.com/53480076/94957983-62302180-050c-11eb-9044-1c3fb435d16a.png)

**Comment by PrathamDogra** [comment]
I would like to go through this issue.

**Comment by imabp** [comment]
Great Go ahead. 
If you need any help do comment in the thread

**Comment by sandy9808** [comment]
I will also try it..

**Comment by imabp** [comment]
@sandy9808 @prachi-ag 

## I am putting this issue for now on HOLD
## Reason:
We are updating the dummy APIs . so event page is not receiving the correct format of response.



```js
This issue is faced only locally by contributors because of dummy APIs are not  updated after critical commits regarding airtable.

```

**Comment by imabp** [comment]
By tomorrow we will resolve the backend dummy apis field configs. So for now, please you can contribute to other issues, or create other issues. or features or bug. 

Thankyou .
### Sorry for the inconvenience

**Comment by imabp** [comment]
@PrathamDogra @sandy9808 

I have updated the dummy keys in `master` and as well as in `development` branches. 

Happy Contributing. 
@PrathamDogra  the issue of slice not defined will be resolved now as airtable is sending correct response

Please see the updated dummy api keys [here](https://github.com/Ninja-Developers/Tech_Phantoms_website#-api-key-installation-dummy):

**Comment by ashuvssut** [comment]
can i get this assigned to me?

**Comment by imabp** [comment]
Sure Go Ahead @ashuvssut  
We are actually migrating to Material UI , it would be great, if you redesign the things using Material UI only.

Make sure, you properly read the Readme and project guidelines before contributing. :)

**Comment by ashuvssut** [comment]
Sir I know decent HTML CSS JS (ES6) ...you can view my project made in pure HTML CSS JS [here](blessnbliss.org).

I just want to say that i am learning react. thats why i want to contribute here. sure i will learn material ui too. and thats why my PR would take some time. hope you understand why i will be submitting taking a quite some time...

**Comment by imabp** [comment]
@Souvikns What you say ?

**Comment by ashuvssut** [comment]
@imabp 

which one is required [this one](https://github.com/Tech-Phantoms/Tech_Phantoms_website/blob/wireframes/wireframes/img-export/event-2-design.png) or [this one](https://github.com/Tech-Phantoms/Tech_Phantoms_website/blob/wireframes/wireframes/img-export/events-page-design-wireframe%402x.png)

Can you tell what does this **filters** button does 
![image](https://user-images.githubusercontent.com/60546840/106108052-9b645100-60fc-11eb-9ae7-b0397caa72c0.png)

If this filter button is to just separate out **upcoming events** and **previous events**, can i use material-ui tabs instead and remove filter button?
