### ISSUE TITLE
More gentle cards in home page 

### ISSUE THREAD

**Issue by AbhinavReddy-Dev** [Tech-Phantoms/Tech_Phantoms_website#172]
**Is your feature request related to a problem? Please describe.**
This is not a problem in code but it is for the visitor's eyes, and feel of the website.

**Describe the solution you'd like**
Current cards design that we have is similar to examples on w3Schools website, what we need is something that looks closer to bootstrap or materialUI that have shadows and color hierarchy. 

**Additional context**

Current design
![Screenshot 2020-10-05 at 09 46 03](https://user-images.githubusercontent.com/33514341/95039870-97e13000-06ef-11eb-9819-c972de3ad7bb.png)

**Use these for reference**

[Material-UI](https://material-ui.com/components/cards/#simple-card)

[Material.io](https://material.io/components/cards#actions)

**Comment by imabp** [comment]
Actually I am working on rest content for landing page. 
The card looks bit common, if you want you can modify it. Give some aesthetic look
I am building up rest content for landing page. 
Go Ahead @AbhinavReddy-Dev

**Comment by AbhinavReddy-Dev** [comment]
Awesome, what fonts are we using for headings?

**Comment by rebekris** [comment]
hi everyone! can I participate?

**Comment by AbhinavReddy-Dev** [comment]
@imabp I'll try to make a PR today and also I have raised an issue on clad, could you please check it?

**Comment by AbhinavReddy-Dev** [comment]
@imabp are you working on alignment and sizing assets for home page? I see there is an absent uniform sizing for the technologies images (section above footer).

**Comment by imabp** [comment]
yaa actually i am working on that.. i just pushed it. so that .. we dont loose community engagement. It will take bit time... Thanks bro.. for this..

**Comment by AbhinavReddy-Dev** [comment]
Cool bro, I am working on the cards, Material UI feels more like Styled components with extra work but saves us from the burden of making it responsive.

**Comment by imabp** [comment]
Go Ahead I have already assigned you this 😊 @AbhinavReddy-Dev
