### ISSUE TITLE
Changing File Structure

### ISSUE THREAD

**Issue by Souvikns** [Tech-Phantoms/Tech_Phantoms_website#184]
We are adopting a new file-structure for our codebase. We are gonna migrate old components to the new file-structure. 

### Pages
- [x] Home - @imabp 
- [x] Event - @Souvikns 
- [x] Team - @imabp 
- [x] Project - @Souvikns

**Comment by Souvikns** [comment]
I guess all is done.

**Comment by Souvikns** [comment]
I guess this issue is fixed

**Comment by imabp** [comment]
I am still fixing the navbar stuff, will send PR then

**Comment by imabp** [comment]
and some proptypes for navbar also there thats why
