### ISSUE TITLE
Edits in Home page

### ISSUE THREAD

**Issue by puranjay123** [Tech-Phantoms/Tech_Phantoms_website#217]
I have suggested some edits on the homepage from which it looks more interactive.  
![Edits tech phatom](https://user-images.githubusercontent.com/55429956/96859593-4d95d800-147f-11eb-9f77-13cbffc90b77.png)

**Comment by puranjay123** [comment]
@imabp @Souvikns some suggested edits for the homepage

**Comment by Sloth-Panda** [comment]
hey, can i get this issue?

**Comment by Ak-panchal** [comment]
hey, can i get this issue?

**Comment by shrutijha16** [comment]
hey ,can i work on this issue?
