### ISSUE TITLE
Microsoft Student Partners text should be linked.

### ISSUE THREAD

**Issue by aniketsingh98571** [Tech-Phantoms/Tech_Phantoms_website#237]
**Is your feature request related to a problem? Please describe.**
On the home page of your website, the Microsoft student partner text can be linked with the website of MLSA.

**Describe the solution you'd like**
By linking these, the newbies who do not know what "Microsoft Student Partner is?" will get to know about the program and he/she can register in it.

**Describe alternatives you've considered**
No alternatives

**Additional context**
No

**Comment by yashsehgal** [comment]
Hey @aniketsingh98571, I am interested in this issue. Could you suggest to me how may I start with this one?

**Comment by aniketsingh98571** [comment]
This issue is specifically for the project maintainers to look at, if they allow then only we can work on it.

**Comment by aniketsingh98571** [comment]
@Souvikns  @imabp

**Comment by Souvikns** [comment]
refer #238

**Comment by Kp779** [comment]
hello @aniketsingh98571 ,
I would like to resolve this issue. Allow me to go ahead with it.

**Comment by kanishkaa24** [comment]
Hey!
I would love to work on this.

**Comment by chehak123** [comment]
hii 
i would like to work on this issue

**Comment by Khimit** [comment]
hello,
     I would like to resolve this issue.

**Comment by imabp** [comment]
@aniketsingh98571 You can work on the issue up. 
As we are following first come-first serve principle.

**Comment by imabp** [comment]
@aniketsingh98571 , 
Make sure, you put these things too
`rel="noopener noreferrer"`
`target="_blank"`

**Comment by vedikaag99** [comment]
@imabp Can I work on this ?

**Comment by Amit366** [comment]
Is this issue open??
