### ISSUE TITLE
New design for events page

### ISSUE THREAD

**Issue by Souvikns** [Tech-Phantoms/Tech_Phantoms_website#239]
## Current Design 
![Screenshot 2020-12-22 at 4 21 35 PM](https://user-images.githubusercontent.com/41781438/102880741-d0ccad80-4471-11eb-886f-50cea5a44333.png)

![Screenshot 2020-12-22 at 4 21 42 PM](https://user-images.githubusercontent.com/41781438/102880739-cf9b8080-4471-11eb-9005-63b304ffaa58.png)

---

We need to redesign this page keeping the overall theme same as the other pages. I think we can have two sections namely 
- upcoming events
- previous events

## TODO 
- [x] Finalize the mockup before coding 
- [ ] Convert the mockup in react 

> I will update with mockups later.

**Comment by SuNiL-Chau** [comment]
Hi @Souvikns can I give it a shot?

**Comment by patel-atul** [comment]
Hey @Souvikns can I design mockup for his page

**Comment by Souvikns** [comment]
@SuNiL-Chau, this issue is kinda a general overview of the problem, and what we need to do, After we decide on the mockup, we can start with coding, right now this is just a discussion issue you can put up with any idea or mockup. After we decide on the mockup I will create another issue linking this one.

**Comment by Souvikns** [comment]
@patel-atul for now this is an open issue anyone can give ideas and submit mockups. Feel free to post any idea you have, we are open to ideas.

**Comment by Souvikns** [comment]
![Events Page](https://user-images.githubusercontent.com/41781438/103156870-44a0ea00-47d3-11eb-8b78-39acbc004a77.png)

---
So I was just creating a rough mockup, I was thinking we could have two tabs for upcoming events where we can show all the new events, we can write the logic for updating upcoming events and pushing them to the previous section by checking the date and time against current date and time. 

> Let me know your thoughts @imabp

**Comment by yashsehgal** [comment]
Hey, I am interested in this. Shall I start working on this? I am currently working on the design. I can provide you with the mockups if you want?

**Comment by Souvikns** [comment]
@yashsehgal go ahead, post your ideas, nothing is final right now, I had posted a mockup you can take some idea from there as well.

**Comment by SuNiL-Chau** [comment]
> @SuNiL-Chau, this issue is kinda a general overview of the problem, and what we need to do, After we decide on the mockup, we can start with coding, right now this is just a discussion issue you can put up with any idea or mockup. After we decide on the mockup I will create another issue linking this one.

Okay cool let me try

**Comment by kanishkaa24** [comment]
Hey!
I would love to work on this. Please assign.

**Comment by SuNiL-Chau** [comment]
Hey @Souvikns  and @imabp kindly have look at the figma design and provide feedback
https://www.figma.com/file/lKzoRMap6HRR5V1mYynWDe/tech-phantom-event-page?node-id=0%3A1

**Comment by Souvikns** [comment]
> Hey @Souvikns and @imabp kindly have look at the figma design and provide feedback
> https://www.figma.com/file/lKzoRMap6HRR5V1mYynWDe/tech-phantom-event-page?node-id=0%3A1

This is cool, we can go with this design. nice @SuNiL-Chau

**Comment by SuNiL-Chau** [comment]
> > Hey @Souvikns and @imabp kindly have look at the figma design and provide feedback
> > https://www.figma.com/file/lKzoRMap6HRR5V1mYynWDe/tech-phantom-event-page?node-id=0%3A1
> 
> This is cool, we can go with this design. nice @SuNiL-Chau

Thank you @Souvikns  I appreciate :) but had a question about cards they look good but can be improved so would like to improve them?

**Comment by Souvikns** [comment]
That could be another issue, @SuNiL-Chau what do you have in your mind for the design of the cards.

**Comment by SuNiL-Chau** [comment]
> That could be another issue, @SuNiL-Chau what do you have in your mind for the design of the cards.

The badges can be on the side of the titles of the events, the timing below as it is , Checkout button to be primary btn with brand color & recording or other btn as a secondary button.

the drop downbtn to be removed and move the description below titles with only two lines and have a truncated click able as secondary color (read more) and then show more info.

no borders & soft spread shadow

**Comment by yashsehgal** [comment]
## A Rough Mockup Design
![events-page-design-wireframe@2x](https://user-images.githubusercontent.com/62352288/103169334-a6f3fc00-4860-11eb-8c90-4e56afa6399a.png)

This is my approach to UI Design for this page. Hope you'll like it.

**Comment by Souvikns** [comment]
Yeah, how about we use @yashsehgal cards with @SuNiL-Chau design.

**Comment by yashsehgal** [comment]
> Yeah, how about we use @yashsehgal cards with @SuNiL-Chau design.

It will be a pleasure, So what I have to do now?

**Comment by SuNiL-Chau** [comment]
> Yeah, how about we use @yashsehgal cards with @SuNiL-Chau design.

the cards are missing the info part let me create a varient then you can choose 1 @Souvikns

**Comment by Souvikns** [comment]
Well I was waiting till 8 pm before finalizing, but if no one else is working on this I can start creating the issues for the development.

**Comment by Souvikns** [comment]
> > Yeah, how about we use @yashsehgal cards with @SuNiL-Chau design.
> 
> the cards are missing the info part let me create a varient then you can choose 1 @Souvikns

Ok @SuNiL-Chau then export a final png and then we can start with the coding.

**Comment by SuNiL-Chau** [comment]
> > > Yeah, how about we use @yashsehgal cards with @SuNiL-Chau design.
> > 
> > 
> > the cards are missing the info part let me create a varient then you can choose 1 @Souvikns
> 
> Ok @SuNiL-Chau then export a final png and then we can start with the coding.

Okay cool

**Comment by yashsehgal** [comment]
And what about my design, I can redesign it for you if you want.

**Comment by Souvikns** [comment]
@SuNiL-Chau will use your event cards.

**Comment by yashsehgal** [comment]
> @SuNiL-Chau will use your event cards.
Okay Sure

**Comment by SuNiL-Chau** [comment]
Hey @Souvikns & @imabp kindly have a look at the designs and provide feedback in case something needs to be updated
https://www.figma.com/file/lKzoRMap6HRR5V1mYynWDe/tech-phantom-event-page?node-id=0%3A1

**Comment by Souvikns** [comment]
event-2-design do look nice, I guess giving a more uniform page margin might look better, do experiment with it. And export the last board and upload. I will start creating issues for u guys.

**Comment by SuNiL-Chau** [comment]
> event-2-design do look nice, I guess giving a more uniform page margin might look better, do experiment with it. And export the last board and upload. I will start creating issues for u guys.

Okay cool :+1:

**Comment by SuNiL-Chau** [comment]
![event-2-design](https://user-images.githubusercontent.com/46418190/103171778-de6ca380-4874-11eb-9f43-2dc206bd966d.png)

Hi @Souvikns & @imabp  have a look

**Comment by Souvikns** [comment]
So guys we have finalized the design, thanks to @SuNiL-Chau, @yashsehgal. Now we will start coding.

**Comment by yashsehgal** [comment]
How can I get started with the coding part?

**Comment by Souvikns** [comment]
I have created #246 check it out.

**Comment by himanshu007-creator** [comment]
SIR, we need to focus on coders.I would suggest to use dark themed background as mostly coders code at night. But using green color for text is TOO MUCH predictable!
For that i suggest, we will use orange color.
and for font, we will use OSWALD font [ light 300 varient]

so i finally propose these:-
background color:- black
text color [for headings]:- #ff7b00 
font [for heading]:-Source Sans Pro
text color :- white
font [for text]:-Oswald [light 300 varient]
other colors( for image background, etc):- #907163, #3a9e66,

implementing these changes, our website will be similar to this one
![COLOR SCHEME](https://user-images.githubusercontent.com/65963997/103339878-a188f280-4aa8-11eb-851d-f07621ded9cf.jpg)
