### ISSUE TITLE
Enhancement of Home Page

### ISSUE THREAD

**Issue by shivangi00** [Tech-Phantoms/Tech_Phantoms_website#240]
**Is your feature request related to a problem? Please describe.**
The home page of any website is the major attracting force of the organisation as well as the website. I have some ideas for enhancing the same and making it more responsive and updated with today's trend.

1. Having a responsive navigation bar. 
2. The sections look very distraught currently. 
3. Footer needs to be positioned and re- designed. 

**Describe the solution you'd like**

1. Navigation bar of various types can be used - sticky navbar, side navbar, drop down menu etc.
2. Sections can be divided into cards segments and trendy scrolling effects can be implemented.
      - Enough padding between the sections
      - Spreading content instead of compressing it would improve visibility of text (highly recommended). 
      - Using icons/ images/ better styling (highly recommended).
      - Adding testimonials section, any other highlights to home page
3. Align footer content and use appealing color scheme.

**Comment by Souvikns** [comment]
@shivangi00 welcome to our repo, good to have you here. 
Yeah, the designs could be made better. We wanted to update the designs, but I was unable to come up with some good ideas, If we gonna do it, I think we should start with making mockups and all. If you would like to manage this issue I can give you outside collaborators rights that way you can merge and manage issues on your own. 

And for the design what vision do you have, should we go with the current theme and create new components and add new content or change the theme completely.

**Comment by shivangi00** [comment]
@Souvikns Thank you! Yes I would definitely like to manage this issue. I agree we can start with building a mockup first that would make things clearer. 
For the design too I think mockup will be a decent start to know which of the options we can go with.

**Comment by shivangi00** [comment]
This is one of the design themes I came up with. Since the logo reminded me of pacman game. Let me know how you find this or whatever suggestions you have in mind. Also we can connect on figma to make design sharing easier.
My figma profile link - https://www.figma.com/@shivangi00
![image](https://user-images.githubusercontent.com/67910955/103140632-d98ddf80-470e-11eb-9c68-bb1f3e14ad76.png)

**Comment by Souvikns** [comment]
This is kinda cool, so should we have this as a banner, for the website, like the first thing that loads when the user visits our page. 
Also, what are your thought on the theme, as it is dark should we convert the whole website dark?

**Comment by imabp** [comment]
@shivangi00 , Thank you for this. Make sure, you are in the discord channel. I am happy to see you up :) 
Due to ongoing exams, we are bit running slow. But never mind, wont let you down. :)

**Comment by shivangi00** [comment]
> This is kinda cool, so should we have this as a banner, for the website, like the first thing that loads when the user visits our page.
> Also, what are your thought on the theme, as it is dark should we convert the whole website dark?

Yes this is just the banner design, the rest of the content will follow. We can use dark theme, it looks great, just as in Netflix's website and many others. A lot many animations and designs can be incorporated with this theme. Let me know what you think.

**Comment by shivangi00** [comment]
> @shivangi00 , Thank you for this. Make sure, you are in the discord channel. I am happy to see you up :)
> Due to ongoing exams, we are bit running slow. But never mind, wont let you down. :)

Yes I am in the discord channel. I too have my exams, can totally understand. But I'm excited! :)

**Comment by kanishkaa24** [comment]
I would love to work for the implementation of the same.

**Comment by kenkirito** [comment]
can i work on this issue

**Comment by Sloth-Panda** [comment]
@Souvikns  would love to work on this issue please assign this to me
