### ISSUE TITLE
Remove spaces between equals from installation guide under .env keys

### ISSUE THREAD

**Issue by imabp** [Tech-Phantoms/Tech_Phantoms_website#241]

**Comment by patel-atul** [comment]
can I do that

**Comment by Jaspreet099** [comment]
Yes I'm interested in this issue , can you please assign me this.

**Comment by imabp** [comment]
You need to connect on devscript discord channel in order to contribute to the issues tagged with DWOC.

**Comment by Khimit** [comment]
Hello sir,
        I would like to work on this issue. Can you assign this task to me?

**Comment by Jaspreet099** [comment]
I'm not able to find .env file

**Comment by imabp** [comment]
@Jaspreet099 @Khimit @patel-atul 
If you are a DWOC participant, it is open to your contributions.
Please connect over the discord server of DWOC under the channel of techphantoms

**Comment by imabp** [comment]
In order to have a fair contribution, 
@patel-atul , you can go ahead with a PR 

Please note:
This is a readme related PR(doc related work), so you can directly send PR to `master`

**Comment by imabp** [comment]
@Jaspreet099 please read this 
https://imabp.github.io/bestoss/

**Comment by Jaspreet099** [comment]
@imabp ok sir next time i'll take care of it.
