### ISSUE TITLE
Events Page 

### ISSUE THREAD

**Issue by Souvikns** [Tech-Phantoms/Tech_Phantoms_website#255]
This is a sub-issue for #246. 

I will be working on the Events Page writing logic for fetching data and managing state for 
- rendering events list 
- updating the list according to the user's filter choice

## Problem statement 
Currently, the component that is rendering the event list is loading the data and managing the local state. But with the new design, we need to share the same data in more than one component, so we need to load the data a top-level component. 

## Probable Soln 
We getting the data from airtable. We already have created custom hooks to fetch and pass on the data. I will just fetch the data in the `useEffect` hook during `onload` and create a local state on my **event page component**. Any subcomponent that will be needing the data can just accept the event list as a prop value.

**Comment by imabp** [comment]
Here is the final design for holder @Souvikns :
![unknown](https://user-images.githubusercontent.com/53480076/103433568-2e52be00-4c19-11eb-9ebd-9284ffe1914f.png)

**Comment by Souvikns** [comment]
@imabp Update the image in the main issue or the holder sub-issue

**Comment by Souvikns** [comment]
> Here is the final design for holder @Souvikns :
> Edit: As discussed on Discord
> ![unknown](https://user-images.githubusercontent.com/53480076/103433568-2e52be00-4c19-11eb-9ebd-9284ffe1914f.png)

we can make the tags into chips, the way we have done in the repo holder.
