### ISSUE TITLE
Integrate Welcome Bot

### ISSUE THREAD

**Issue by tharunc** [Tech-Phantoms/Tech_Phantoms_website#257]
Hello there,
         I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time as a part of DWOC. Please assign me this issue. 
For reference, kindly check out: https://github.com/apps/welcome

THANK YOU

**Comment by jatinjain001** [comment]
I want to work on this please let me know if it is available.

**Comment by imabp** [comment]
We are closing the following issue. As we already have it on our admin panel on discord :)
