### ISSUE TITLE
Updating the readme with different opnsource programs like hacktoberfest and dwoc

### ISSUE THREAD

**Issue by Sloth-Panda** [Tech-Phantoms/Tech_Phantoms_website#258]
Let me know if this needs to be done

**Comment by Souvikns** [comment]
@imabp

**Comment by imabp** [comment]
No, we dont need it. 
All the details of the project are through communication channel #tech-phantoms on discord of DWOC.

We are more looking for a dedicated contributor. We do conduct google meets and all, to keep the participants in flow.
