### ISSUE TITLE
Automating website

### ISSUE THREAD

**Issue by himanshu007-creator** [Tech-Phantoms/Tech_Phantoms_website#259]
I would like to work on this issue.I will create a script that will enable opening website from CLI.
Please add DWOC label to it and assign me this issue.

**Comment by Souvikns** [comment]
I don't understand clearly, as of now `npm start` command starts the development server and loads the website in a browser automatically.

**Comment by himanshu007-creator** [comment]
> I don't understand clearly, as of now `npm start` command starts the development server and loads the website in a browser automatically.

No sor, my script won't open the loclhost.
It will open your website that's in the description.

**Comment by Souvikns** [comment]
Do you mean the hosted site? Even so, how will it help.

**Comment by imabp** [comment]
> > I don't understand clearly, as of now `npm start` command starts the development server and loads the website in a browser automatically.
> 
> No sir, my script won't open the loclhost.
> It will open your website that's in the description.

@himanshu007-creator 

I got it, you are saying, you will make a script to open the hosted site, as mentioned in package.json.
I could sense this. I dont think it's required as of now.
Feel free to reopen your issue, if you think, you want to say something else.
