### ISSUE TITLE
Add Contributors Table in README.md

### ISSUE THREAD

**Issue by samir-0711** [Tech-Phantoms/Tech_Phantoms_website#260]
Like this
![image](https://user-images.githubusercontent.com/68433936/104681635-cc19b300-5718-11eb-94c6-84c5bd5a2f27.png)

**Comment by samir-0711** [comment]
I would like to work on this.

**Comment by Souvikns** [comment]
This would do but, It would be a pain to update the readme every time, I can assign you this issue if you could create a GitHub action that checks the PR and sees if a new person has made the pr then automatically updates the readme.

**Comment by samir-0711** [comment]
It will be automated.

**Comment by samir-0711** [comment]
Please add any one label "level-1" or "level-2" or "level-3" or "level-4" or "level-5" in this issue.
