### ISSUE TITLE
Content For Landing Page and others

### ISSUE THREAD

**Issue by imabp** [Tech-Phantoms/Tech_Phantoms_website#61]
We need content for the landing page.

**Comment by Priyanshu-official** [comment]
@prachi-ag
 can you explain What type of content you need for the landing page.

**Comment by imabp** [comment]
@Priyanshu-official you can see the current content of **development site** [here](https://devtechphantoms.netlify.app/)
If you have any ideas to improve the content or add something new to the landing page. 
Go ahead with it. ✌

Send a PR to development branch

**Comment by syshcndr** [comment]
Hey @imabp !
I read the existing Content and saw the impact of the Tech Phantoms Members.
And I felt like content in the homepage is focusing on toward becoming the community rather than representing yourself as a community.
I would like to Modify the Existing content to Make it Focus toward "Representing as a Community."

**Comment by imabp** [comment]
@syshcndr- - 

I am glad that you took a time for this. We are happy to have you here.

To contribute for landing page content follow these guidelines. 


1. Create a branch from `development` named as `username-content-landing-page`

2. Send PR to development branch 
3. We will review the content. 
4. PR will be merged to development branch.
5. Periodically,  we will update master branch  with development branch after code cleaning. 
6. Meanwhile your content will be live after mergingg to development branch [here](https://devtechphantoms.netlify.app)

**Comment by shivangi00** [comment]
Hey! I saw your website and read the content. In my opinion, there is a scope of adding a more professional and to the point flare to the website content. I have been into writing content since more than 2 years and I can help you with that, if required.

**Comment by imabp** [comment]
@shivangi00 , I hope you are a DWOC Participant. I am happy to see you up here contributing our project.

Please connect over the DevScript Discord's server under channel techphantoms website
We are going to discuss lot of things before moving on.

**Comment by shivangi00** [comment]
> @shivangi00 , I hope you are a DWOC Participant. I am happy to see you up here contributing our project.
> 
> Please connect over the DevScript Discord's server under channel techphantoms website
> We are going to discuss lot of things before moving on.

Sure! Will connect there.
