### ISSUE TITLE
Hamburger icon in dark mode

### ISSUE THREAD

**Issue by SingingApple** [Tech-Phantoms/Tech_Phantoms_website#66]
Hamburger icon in dark mode blends with the background. Icon color can be changed to white.

**Comment by imabp** [comment]
Assigned. Go Ahead ✌ @SingingApple

**Comment by CodeSarthak** [comment]
@SingingApple  - good catch.  Are you still working on this? Let me know if you need any help :D

**Comment by SingingApple** [comment]
@CodeSarthak Yes, I'm working on it. Sure, I'll let you know if I'll require some help!

**Comment by SingingApple** [comment]
@imabp since the dark theme has been removed from the site, shall I close this issue?

**Comment by imabp** [comment]
@SingingApple we have made a branch `dark-mode` and we are thinking to put it in community v3 release

So you can work on the issue. As we want to complete dark mode in October itself.

Just there is a note, that you need to send PR to `dark-mode` branch regarding dark mode implementation.
