### ISSUE TITLE
Heading not aligned

### ISSUE THREAD

**Issue by ahmad-reza619** [Tech-Phantoms/Tech_Phantoms_website#79]
I'm opening the page on chrome desktop. and the `swith theme` button not aligned with side bar
![Screen Shot 2020-09-25 at 22 16 35](https://user-images.githubusercontent.com/52902060/94284585-c8e99400-ff7c-11ea-9be1-108ce485013b.png)

also, when switching theme, side bar is not visible, because it's black, i think that's not good for readability

![Screen Shot 2020-09-25 at 22 18 32](https://user-images.githubusercontent.com/52902060/94284781-0e0dc600-ff7d-11ea-94f0-3d232155ee40.png)

**Comment by Souvikns** [comment]
@ahmad-reza619 we have a nav component I think putting this button in that component will fix the alignment, for now, it might break the code as the button state is not global.

**Comment by imabp** [comment]
@ahmad-reza619 I would like to look at the issue 
#66  for Hamburger menu
And regarding the switch button
#77 you can refer.

After all above mentioned issues gets merged.  
Then we can think of alignment.

Make sure, you Pull request to `development` branch and core members will review the PR before merging it to `master branch`

**Comment by ahmad-reza619** [comment]
Oh i'm sorry, i didn't notice there's issue about this already

**Comment by ahmad-reza619** [comment]
should i close the issue?

**Comment by imabp** [comment]
@ahmad-reza619 we are planning to implement dark mode in V3 Website, once the V2 (this one) is ready . 
We will be creating a different workflow branch for dark mode. 

So this issue, will be considered then. 

We are planning to do dark mode in this October itself.
